{{- if and .Values.judgingServer.enabled .Values.judgingServer.discoveryRbac.enabled }}
{{- $serviceAccountName := .Values.judgingServer.discoveryRbac.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName }}
  labels:
    app.kubernetes.io/name: croj-judging-server
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $serviceAccountName }}-endpointslices
  labels:
    app.kubernetes.io/name: croj-judging-server
    app.kubernetes.io/instance: {{ .Release.Name }}
rules:
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $serviceAccountName }}-endpointslices
  labels:
    app.kubernetes.io/name: croj-judging-server
    app.kubernetes.io/instance: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $serviceAccountName }}-endpointslices
{{- end }}
