{{- if .Values.applications.enabled }}
{{- range $component := list "frontend" "judging-server" "sandbox" }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $.Release.Name }}-{{ $component }}
  labels:
    {{- include "coderushoj.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $component }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "coderushoj.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $component }}
---
{{- end }}
{{- end }}
